export const birdInfo = [
	{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},{
		name: 'bird 1',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 2',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
	{
		name: 'bird 3',
		species: 'Chim se',
		birthDate: '10/04/2023',
		gender: 'Male',
		status: 'OK',
	},
]