export const cageInfo = [
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    name: "Cage 2",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    name: "Cage 2",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    name: "Cage 1",
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
];
