export const cageInfo = [
  {
    id: 1,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    id: 2,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 10,
  },
  {
    id: 3,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    id: 4,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 5,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    id: 6,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 7,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 8,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    id: 9,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 10,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    id: 11,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    id: 12,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 10,
  },
  {
    id: 13,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "In use",
    capacity: 5,
  },
  {
    id: 14,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 15,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "In use",
    capacity: 10,
  },
  {
    id: 16,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 1",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  {
    id: 17,
    size: "90 x 60 x 90",
    color: "Black",
    area: "300",
    type: "Type 2",
    cageStatus: "Maintainance",
    capacity: 5,
  },
  
];

export const cageStatusEnum =[
  "Active",
  "Deactive",
  "Cancel",
  "Other"
]